improve latex-build

diff --git a/.local/bin/latex-build b/.local/bin/latex-build
--- a/.local/bin/latex-build
+++ b/.local/bin/latex-build
@@ -5,30 +5,57 @@
 # | (_| | |  __/>  < (_| (_) | (_| |  __/ |  | |_| |__   _|
 #  \__,_|_|\___/_/\_\___\___/ \__,_|\___|_|   \___/   |_|  
 # 
-# Copyright (c) 2022 alexcoder04 <https://github.com/alexcoder04>
+# Copyright (c) 2022-2023 alexcoder04 <https://github.com/alexcoder04>
 # 
-# a rather dirty script for compiling latex documents
-
-OUTPUT_DIR="${TMPDIR:-/tmp}/latex-build"
-PDF_READER="zathura"
+# a script for compiling latex documents
 
 . libsh || exit 1
 
 [ -z "$1" ] && die_notify "not given an input file"
+basename="${1##*/}"
+
+OUTPUT_DIR="${TMPDIR:-/tmp}/latex-build-$(echo "$basename" | md5sum | cut -d " " -f1)"
+LATEX_COMPILER="lualatex"
+PDF_READER="zathura"
 
 [ -d "$OUTPUT_DIR" ] || mkdir "$OUTPUT_DIR"
 
-basename="${1##*/}"
+# word count
+if grep -qE '^\s*[^%]*\\wordcount' "$1"; then
+  wordcount="$(pandoc -f latex -t plain "$1" | sed -E 's/\[.{1,3}\]//g' | wc -w)"
+  sed -E "s/^(\\s*[^%]*)\\\\wordcount/\\1\\\\textit{$wordcount words}/g" "$1" > "$OUTPUT_DIR/$basename" || die "Error copying '$1' to temp dir"
+else
+  cp "$1" "$OUTPUT_DIR/$basename" || die "Error copying '$1' to temp dir"
+fi
 
-if ! pdflatex -output-directory "$OUTPUT_DIR" "$1"; then
+cd "$OUTPUT_DIR" || die "Cannot cd to tempdir"
+
+# deal with bibliography
+if grep -qE '^\\usepackage.*{biblatex}$' "$1"; then
+  if [ ! -f "${basename%.*}.pdf" ]; then
+    "$LATEX_COMPILER" "$basename" \
+      || die "Error compiling \"$basename\""
+  fi
+
+  biber "${basename%.*}" \
+    || die "Failed to generate bibliography"
+fi
+
+# compile
+if ! "$LATEX_COMPILER" "$basename"; then
   die_notify "Error compiling \"$basename\""
 fi
 
 case "$2" in
-  --no-display|no-display|build-only|--build-only) exit 0
+  --no-display|no-display|build-only|--build-only) exit 0 ;;
 esac
 
+# show in pdf reader
+echo "$PDF_READER $OUTPUT_DIR/${basename%.*}.pdf"
 if ! pgrep -f "$PDF_READER $OUTPUT_DIR/${basename%.*}.pdf"; then
   "$PDF_READER" "$OUTPUT_DIR/${basename%.*}.pdf" &
+  sleep 0.1
 fi
+
+echo "ALL GOOD, MAN"
 
